<?php
/**
 * Created by PhpStorm.
 * User: Praesidiarius
 * Date: 13.12.2020
 * Time: 19:45
 */
?>
<div class="bg-light row">
    <div class="container py-2">
        <div class="row">
            <div class="col-md-1">
                <i class="fas fa-search text-dark"></i>
            </div>
            <div class="col-md-10">
                <ul class="list-inline">
                    <li class="list-inline-item">
                        Beliebtes
                    </li>
                    <li class="list-inline-item">
                        Burger
                    </li>
                    <li class="list-inline-item">
                        Waffeln
                    </li>
                    <li class="list-inline-item">
                        Salate
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
