<?php
/**
 * Created by PhpStorm.
 * User: Praesidiarius
 * Date: 13.12.2020
 * Time: 18:55
 */


echo $this->partial('shop/partials/zipselector', []);
?>
<div class="container">

    <div style="padding-top:120px; text-align:center;">
        <h1>Hello world!</h1>
        <p class="lead">Remove this content or build upon it.<br>
            For documentation and examples: <a href="http://getbootstrap.com/" target="_blank">getbootstrap.com</a><br>
            Here is a <a href="newpage.html">link to another page</a></p>
    </div>


</div>
