<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="This is a boilerplate for a Bootstrap 4.1.1 project">
    <meta name="keywords" content="HTML, CSS, JS, Sass, JavaScript, framework, bootstrap, front-end, frontend, web development">
    <meta name="author" content="Henrik H. Boelsmand">
    <title>Annas Burger- und Waffelhouse</title>
    <link rel="shortcut icon" href="favicon.ico">

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>

    <!-- build:css -->
    <link rel="stylesheet" href="/vendor/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/vendor/select2/dist/css/select2.min.css">
    <link rel="stylesheet" href="/vendor/sweetalert2/dist/sweetalert2.min.css">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
          integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
          crossorigin=""/>
    <link rel="stylesheet" href="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css" />
    <link rel="stylesheet" href="/foodorder/css/web.css">
    <!-- endbuild -->
</head>

<body>
<!--
<nav class="navbar navbar-expand-md navbar-dark text-center" style="background: #28292e;" id="plc-shop-header">
    <a class="navbar-brand" href="/"><img src="/foodorder/img/logo.png" /></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href=".">Home <span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <?php if(isset(\Application\Controller\CoreController::$oSession->oUser)) { ?>
        <div class="my-2 my-lg-0">
            <a class="btn btn-secondary" href="/home">Backend</a>
        </div>
        <?php } ?>
    </div>
</nav>
-->
<nav class="navbar bg-dark">
    <div class="container py-2">
        <ul class="nav navbar-nav pull-sm-left">

        </ul>
        <ul class="nav navbar-nav navbar-logo mx-auto">
            <li class="nav-item">
                <a class="navbar-brand" href="/"><img src="/foodorder/img/logo.png" style="max-height:150px; margin-top:-12px;" /></a>
            </li>
        </ul>
        <ul class="nav navbar-nav pull-sm-right">

        </ul>
    </div>
</nav>

<?php
/**
 * Print Flashmessenger messages (alerts)
 */
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s style="">
                                 <ul><li>')
    ->setMessageSeparatorString('</li><li>')
    ->setMessageCloseString('</li></ul></div>');
echo $flash->render('error',   ['alert', 'alert-dismissible', 'alert-danger', 'alert-plc']);
echo $flash->render('info',    ['alert', 'alert-dismissible', 'alert-info', 'alert-plc']);
echo $flash->render('default', ['alert', 'alert-dismissible', 'alert-info', 'alert-plc']);
echo $flash->render('warning', ['alert', 'alert-dismissible', 'alert-warning', 'alert-plc']);
echo $flash->render('success', ['alert', 'alert-dismissible', 'alert-success', 'alert-plc']);?>

<?=$this->content?>

<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
        integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
        crossorigin=""></script>
<script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>
<script src="https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js"></script>
<!-- build:js -->
<?php
echo $this->inlineScript()
    //->prependFile($this->basePath('/vendor/sweetalert2/dist/sweetalert2.min.js'))
    ->prependFile($this->basePath('/vendor/select2/dist/js/select2.full.min.js'))
    ->prependFile($this->basePath('/vendor/bootstrap/dist/js/bootstrap.min.js'))
    ->prependFile($this->basePath('/vendor/jquery/dist/jquery.min.js'));
?>

<script src="https://kit.fontawesome.com/0e8b0a2463.js" crossorigin="anonymous"></script>
<!-- endbuild -->
</body>

</html>