<?php
use Application\Controller\CoreController;
?>

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Einstellungen</h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">
                        Onlineshop
                    </div>
                    <div class="col-md-6 text-right">
                        <?php $sChecked = (CoreController::$aGlobalSettings['shop-open'] == 1) ? 'checked' : ''?>
                        <input class="plc-toggle-shop" type="checkbox" <?=$sChecked?> data-toggle="toggle" data-size="md" data-onstyle="success" data-offstyle="danger" data-on="Geöffnet" data-off="Geschlossen">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card">
            <div class="card-header">

                <h3 class="card-title">Liefergebiete</h3>
            </div>
            <div class="card-body p-0">
                <ul class="list-group">

                </ul>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Design</h3>
            </div>
            <div class="card-body p-0">
                <ul class="list-group">

                </ul>
            </div>
        </div>
    </div>
</div>

<?php

//     <link rel="stylesheet" href="/vendor/bootstrap4-toggle/css/bootstrap4-toggle.min.css">
$this->headLink()
    ->appendStylesheet($this->basePath('/vendor/bootstrap4-toggle/css/bootstrap4-toggle.min.css'));

$this->inlineScript()
    ->appendFile($this->basePath('/vendor/bootstrap4-toggle/js/bootstrap4-toggle.min.js'))
    ->appendFile($this->basePath('/foodorder/js/index.js'));