<?php
/**
 * Created by PhpStorm.
 * User: Praesidiarius
 * Date: 11.01.2021
 * Time: 19:33
 */
?>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-8">
                <h2><?=$oJob->getLabel()?></h2>
            </div>
            <div class="col-md-4">
                <?php if($oJob->getSelectFieldID('state_idfs') == 15) { ?>
                <form action="/foodorder/backend/confirm" method="POST">
                    <input type="hidden" name="job_id" value="<?=$oJob->getID()?>" />
                    <select name="deliverytime_est">
                        <option value="30">30 Min</option>
                        <option value="45">45 Min</option>
                        <option value="60">60 Min</option>
                        <option value="75">75 Min</option>
                        <option value="90">90 Min</option>
                    </select>
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-check"></i> Bestätigen
                    </button>
                </form>
                <?php } ?>

                <?php if($oJob->getSelectFieldID('state_idfs') == 17) {
                    $data = 'https://annas.1plc.ch/foodorder/api/delivery/'.$oJob->getID();

                    echo '<img src="'.(new \chillerlan\QRCode\QRCode)->render($data).'" alt="QR Code" />';
                    ?>

                <?php } ?>
            </div>
        </div>
    </div>
    <div class="card-body">
        <h2>Bestellung</h2>
        <ul class="list-group">
        <?php
        if(count($oJob->aPositions) > 0) {
            foreach($oJob->aPositions as $oPos) { ?>
            <li class="list-group-item">
                <?=$oPos->amount?>x <?=$oPos->oArticle->getLabel()?>
            </li>
            <?php
            }
        }
        ?>
        </ul>
    </div>
    <div class="card-body">
        <h2>Lieferung</h2>
        Nathanael Kammermann
        Sackstrass 34
        8460 Marthalen
    </div>
</div>